### PR TITLE
Fix typedoc generation

### LINKED ISSUE #211: Typedoc generating incorrect modules docs
**Describe the Bug**
When running typedoc it's generating incorrect modules docs, presenting indexes which are full of repeated links such as the snippet below from `docs/modules.html`:

```html
<section class="tsd-index-section ">
	<h3>Modules</h3>
	<ul class="tsd-index-list">
		<li class="tsd-kind-module"><a href="modules/common_util.html" class="tsd-kind-icon">common/util</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical.html" class="tsd-kind-icon">illogical</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_common.html" class="tsd-kind-icon">illogical/common</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_common.html" class="tsd-kind-icon">illogical/common</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_comparison.html" class="tsd-kind-icon">illogical/expression/comparison</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_comparison.html" class="tsd-kind-icon">illogical/expression/comparison</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_comparison.html" class="tsd-kind-icon">illogical/expression/comparison</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_comparison.html" class="tsd-kind-icon">illogical/expression/comparison</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_comparison.html" class="tsd-kind-icon">illogical/expression/comparison</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_comparison.html" class="tsd-kind-icon">illogical/expression/comparison</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_comparison.html" class="tsd-kind-icon">illogical/expression/comparison</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_comparison.html" class="tsd-kind-icon">illogical/expression/comparison</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_comparison.html" class="tsd-kind-icon">illogical/expression/comparison</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_comparison.html" class="tsd-kind-icon">illogical/expression/comparison</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_comparison.html" class="tsd-kind-icon">illogical/expression/comparison</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_comparison.html" class="tsd-kind-icon">illogical/expression/comparison</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_logical.html" class="tsd-kind-icon">illogical/expression/logical</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_logical.html" class="tsd-kind-icon">illogical/expression/logical</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_logical.html" class="tsd-kind-icon">illogical/expression/logical</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_logical.html" class="tsd-kind-icon">illogical/expression/logical</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_logical.html" class="tsd-kind-icon">illogical/expression/logical</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_logical.html" class="tsd-kind-icon">illogical/expression/logical</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_prefix.html" class="tsd-kind-icon">illogical/expression/prefix</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_expression_suffix.html" class="tsd-kind-icon">illogical/expression/suffix</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_operand.html" class="tsd-kind-icon">illogical/operand</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_operand.html" class="tsd-kind-icon">illogical/operand</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_operand.html" class="tsd-kind-icon">illogical/operand</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_operand.html" class="tsd-kind-icon">illogical/operand</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_parser.html" class="tsd-kind-icon">illogical/parser</a></li>
		<li class="tsd-kind-module"><a href="modules/illogical_parser.html" class="tsd-kind-icon">illogical/parser</a></li>
	</ul>
</section>
```

This is likely being caused by a combination of a breaking change in typedoc itself along with repeated typedoc annotations such as `@module illogical/expression/comparison` in illogical source files.

**To Reproduce**
In a terminal window run `npm run docs` from illogical root folder.

**Expected Behavior**
Each repeated link in the indexes should be unique and pointing to different elements of each referenced module.

### PR DESCRIPTION
**Pull request by rpedrosanto**
# Description
* Remove `@module` annotations from TS source files to fix typedoc generation
* Update NPM packages

### Screenshots
Before:
image

After:
image

#### References
- Closes #211

### CODE REVIEW

**Comment by luiz290788** [comment]
do we want to upgrade dependencies as part of this PR?

**Comment by rpedrosanto** [comment]
> do we want to upgrade dependencies as part of this PR? Maybe, let's upgrade dependencies in a separate pr and then apply these changes.

I'll split it in a separate PR.

**Review by luiz290788 — APPROVED** [review]
LGTM, @davidhorak any comments?

**Comment by davidhorak** [comment]
> LGTM, @davidhorak any comments?

Just a question @rpedrosanto ... does the generated documentation still respect the modules split? Maybe a screenshot of before / after documentation would be nice here.

**Comment by rpedrosanto** [comment]
> > LGTM, @davidhorak any comments?
> 
> Just a question @rpedrosanto ... does the generated documentation still respect the modules split? Maybe a screenshot of before / after documentation would be nice here.

It does. I have added screenshots to the description.

**Comment by davidhorak** [comment]
> > > LGTM, @davidhorak any comments?
> > 
> > 
> > Just a question @rpedrosanto ... does the generated documentation still respect the modules split? Maybe a screenshot of before / after documentation would be nice here.
> 
> It does. I have added screenshots to the description.

Awesome! thank you @rpedrosanto!

**Pull request merged**
